(load-extension "./libguile-rocksdb" "init")
(use-modules (rocksdb)
             (rocksdb options))

(let ([opts (rocksdb-options-create)])
  (rocksdb-options-increase-parallelism! opts 4)
  (rocksdb-options-optimize-level-style-compaction! opts 0)
  (rocksdb-options-set-create-if-missing! opts 1)
  (let ([db (rocksdb-open opts "/tmp/rocksdb_simple_example")])
    (display "opts: ")
    (display opts)
    (newline)
    (display "db: ")
    (display db)
    (newline)))
